name: Deploy Version on Tag

on:
  workflow_run:
    workflows: [Semantic Release]
    types:
      - completed
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Tag
        uses: actions/download-artifact@v4
        with:
          name: tag
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Load Tag Name
        run: |
          source tag.env
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          chmod +x ./deploy-with-tag.sh
          ./deploy-with-tag.sh

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The Semantic Release workflow failed'